# Generated by Django 6.0.2 on 2026-02-23 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin_app', '0001_initial'),
        ('Core_app', '0001_initial'),
        ('Seller_app', '0001_initial'),
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_app.category'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_app.category'),
        ),
        migrations.AddField(
            model_name='categorydiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.discount'),
        ),
        migrations.AddField(
            model_name='categoryofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.offer'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.discount'),
        ),
        migrations.AddField(
            model_name='offerdiscountbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.offer'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.orderitem'),
        ),
        migrations.AddField(
            model_name='platformcommission',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.sellerprofile'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.discount'),
        ),
        migrations.AddField(
            model_name='productdiscountbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.product'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.offer'),
        ),
        migrations.AddField(
            model_name='productofferbridge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller_app.product'),
        ),
    ]
