# Generated by Django 6.0.2 on 2026-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=models.FloatField(help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='length',
            field=models.FloatField(help_text='Length in cm', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=models.FloatField(help_text='Width in cm', null=True),
        ),
    ]
