# Generated by Django 6.0.2 on 2026-02-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller_app', '0003_alter_productimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='product_images',
        ),
    ]
