# Generated by Django 6.0.2 on 2026-02-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_app', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
